// <auto-generated />
namespace EnouFlowOrgMgmtLib.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addBizEntityRelationOnOrgSchema : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addBizEntityRelationOnOrgSchema));
        
        string IMigrationMetadata.Id
        {
            get { return "201701040709035_add-BizEntityRelationOnOrgSchema"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
